<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>5d946ae7-8ba8-45a2-a5ee-87a8983f7db6</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Livekit.Server.Sdk.Dotnet" Version="1.2.2" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.5" />
    <PackageReference Include="Microsoft.Azure.Cosmos" Version="3.60.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\polrob.Shared\polrob.Shared.csproj" />
  </ItemGroup>

</Project>
