using System.Text;
using SkiaSharp;

if (args.Length != 2)
{
    throw new ArgumentException("Usage: PolRob.AssetBounds <raw-assets-directory> <generated-csharp-file>");
}

var rawAssetsDirectory = Path.GetFullPath(args[0]);
var outputPath = Path.GetFullPath(args[1]);
if (!Directory.Exists(rawAssetsDirectory))
{
    throw new DirectoryNotFoundException(rawAssetsDirectory);
}

var mapAssets = FindAssets(Path.Combine(rawAssetsDirectory, "MapAssets"), "*.png", SearchOption.AllDirectories, 16);
var characterAssets = FindAssets(rawAssetsDirectory, "char_*.png", SearchOption.TopDirectoryOnly, 32);
var generatedSource = GenerateSource(mapAssets, characterAssets);

Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);
File.WriteAllText(outputPath, generatedSource, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));

Console.WriteLine($"Generated bounds for {mapAssets.Count} map assets and {characterAssets.Count} character assets.");

List<AssetMetadata> FindAssets(string directory, string pattern, SearchOption searchOption, byte minimumAlpha)
{
    if (!Directory.Exists(directory))
    {
        return [];
    }

    return Directory.GetFiles(directory, pattern, searchOption)
        .OrderBy(path => path, StringComparer.Ordinal)
        .Select(path => Analyze(path, minimumAlpha))
        .ToList();
}

AssetMetadata Analyze(string path, byte minimumAlpha)
{
    using var bitmap = SKBitmap.Decode(path)
        ?? throw new InvalidOperationException($"Could not decode PNG asset: {path}");

    var left = bitmap.Width;
    var top = bitmap.Height;
    var right = 0;
    var bottom = 0;

    // This work intentionally runs in the build tool, never in the game UI thread.
    // Pixels returns one managed array, avoiding millions of native GetPixel calls.
    var pixels = bitmap.Pixels;
    for (var index = 0; index < pixels.Length; index++)
    {
        if (pixels[index].Alpha < minimumAlpha)
        {
            continue;
        }

        var x = index % bitmap.Width;
        var y = index / bitmap.Width;
        left = Math.Min(left, x);
        top = Math.Min(top, y);
        right = Math.Max(right, x + 1);
        bottom = Math.Max(bottom, y + 1);
    }

    if (right <= left || bottom <= top)
    {
        left = 0;
        top = 0;
        right = bitmap.Width;
        bottom = bitmap.Height;
    }

    var logicalName = Path.GetRelativePath(rawAssetsDirectory, path).Replace(Path.DirectorySeparatorChar, '/');
    return new AssetMetadata(logicalName, bitmap.Width, bitmap.Height, left, top, right, bottom);
}

static string GenerateSource(
    IReadOnlyList<AssetMetadata> mapAssets,
    IReadOnlyList<AssetMetadata> characterAssets)
{
    var source = new StringBuilder();
    source.AppendLine("// <auto-generated />");
    source.AppendLine("using SkiaSharp;");
    source.AppendLine();
    source.AppendLine("namespace polrob.Client;");
    source.AppendLine();
    source.AppendLine("internal static class GeneratedAssetBounds");
    source.AppendLine("{");
    WriteDictionary(source, "MapAssets", mapAssets);
    source.AppendLine();
    WriteDictionary(source, "CharacterAssets", characterAssets);
    source.AppendLine();
    source.AppendLine("    public static SKRect GetMap(string assetPath, int width, int height) =>");
    source.AppendLine("        Get(MapAssets, assetPath, width, height);");
    source.AppendLine();
    source.AppendLine("    public static SKRect GetCharacter(string assetPath, int width, int height) =>");
    source.AppendLine("        Get(CharacterAssets, assetPath, width, height);");
    source.AppendLine();
    source.AppendLine("    private static SKRect Get(");
    source.AppendLine("        IReadOnlyDictionary<string, (int Width, int Height, SKRect Bounds)> assets,");
    source.AppendLine("        string assetPath,");
    source.AppendLine("        int width,");
    source.AppendLine("        int height)");
    source.AppendLine("    {");
    source.AppendLine("        if (!assets.TryGetValue(assetPath, out var metadata))");
    source.AppendLine("        {");
    source.AppendLine("            throw new InvalidOperationException($\"Precomputed bounds are missing for '{assetPath}'. Rebuild the client project.\");");
    source.AppendLine("        }");
    source.AppendLine();
    source.AppendLine("        if (metadata.Width != width || metadata.Height != height)");
    source.AppendLine("        {");
    source.AppendLine("            throw new InvalidOperationException(");
    source.AppendLine("                $\"Precomputed bounds for '{assetPath}' describe {metadata.Width}x{metadata.Height}, but the packaged image is {width}x{height}. Rebuild the client project.\");");
    source.AppendLine("        }");
    source.AppendLine();
    source.AppendLine("        return metadata.Bounds;");
    source.AppendLine("    }");
    source.AppendLine("}");
    return source.ToString();
}

static void WriteDictionary(StringBuilder source, string name, IReadOnlyList<AssetMetadata> assets)
{
    source.AppendLine($"    private static readonly IReadOnlyDictionary<string, (int Width, int Height, SKRect Bounds)> {name} =");
    source.AppendLine("        new Dictionary<string, (int, int, SKRect)>(StringComparer.Ordinal)");
    source.AppendLine("        {");
    foreach (var asset in assets)
    {
        var escapedName = asset.Name.Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\"", "\\\"", StringComparison.Ordinal);
        source.AppendLine(
            $"            [\"{escapedName}\"] = ({asset.Width}, {asset.Height}, new SKRect({asset.Left}, {asset.Top}, {asset.Right}, {asset.Bottom})),");
    }
    source.AppendLine("        };");
}

internal sealed record AssetMetadata(
    string Name,
    int Width,
    int Height,
    int Left,
    int Top,
    int Right,
    int Bottom);
