<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="SkiaSharp" Version="3.119.2" />
    <ProjectReference Include="../../polrob.Shared/polrob.Shared.csproj" />
    <Compile Include="../../polrob.Client/TownMapRenderer.cs" Link="TownMapRenderer.cs" />
    <Compile Include="../../polrob.Client/IMapRenderer.cs" Link="IMapRenderer.cs" />
    <Compile Include="../../polrob.Client/ClassicTownMapRenderer.cs" Link="ClassicTownMapRenderer.cs" />
  </ItemGroup>
</Project>
